FROM python:3.8-alpine
RUN apk update
RUN apk --update-cache add \
	gcc \
	g++ \
	make \
	gfortran \
	openblas-dev \
	musl \
	python3-dev \
	libffi-dev \
	lapack-dev \
	zeromq-dev \
	llvm \
	zlib \
	zlib-dev \
	jpeg-dev \
	llvm-dev